services:
  backend:
    platform: linux/amd64
    image: ghcr.io/abialqhafari/gamatecha-be
    # build: ../backend
    ports:
      - '3000:3001'
    env_file:
      - .env

  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - ./redis_data:/data