services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT_EXPOSE}:5432'
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
      # - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    restart: unless-stopped

  backend:
    platform: linux/amd64
    image: ghcr.io/
    # build: ../backend
    ports:
      - '${BACKEND_PORT_EXPOSE}:3000'
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      restart: unless-stopped
    depends_on:
      - db
      - redis
